spring:
  security:
    user:
      name: user
      password: password
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/user
    password: 1234
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

server:
  port: 8082

aw:
  auth:
    provider-uri: "http://localhost:8082"
