spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/post
    password: 1234
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/oauth2/jwks
#          jwk-set-uri: http://localhost:8082/oauth2/jwks

server:
  port: 8081

aw:
  user-api:
    url: 'http://localhost:8080'
    encoded-credentials: 'YWRtaW5AZW1haWwuY29tOmFkbWlu'
